### ISSUE TITLE
I am not able to understand what this mean here , can you provide the meaning

### ISSUE THREAD

**Issue by Vps79-cpu** [vishvAsa/AgamaH_shaivaH#9]
अथ स्त्रीपुंसयोः पायुं गच्छतां प्रायश्चित्तमाह गच्छतामित्यादिना ।
पुंसः पुरुषस्य स्त्रियाश्च पायुं गुदं कामतो गच्छतां दुरात्मनां भूभृता राज्ञा शम्भुशासनाद्वध एव विधातव्यः 

Its in maha nirvana tantra chapter 11 , 44)

**Comment by vvasuki** [comment]
Penalty for sodomy is said to be execution by the king per shiva's order.

Curious how you came upon this though.
